In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('IMDB Dataset.csv')

In [3]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
print(df.shape)

(50000, 2)


In [5]:
import nltk

In [6]:
example = df['review'][5]
print(example)

Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it's not preachy or boring. It just never gets old, despite my having seen it some 15 or more times in the last 25 years. Paul Lukas' performance brings tears to my eyes, and Bette Davis, in one of her very few truly sympathetic roles, is a delight. The kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. And the mother's slow awakening to what's happening in the world and under her own roof is believable and startling. If I had a dozen thumbs, they'd all be "up" for this movie.


In [7]:
tokens = nltk.word_tokenize(example)
tokens[:10]

['Probably',
 'my',
 'all-time',
 'favorite',
 'movie',
 ',',
 'a',
 'story',
 'of',
 'selflessness']

In [8]:
tagged = nltk.pos_tag(tokens)
tagged[:10]

[('Probably', 'RB'),
 ('my', 'PRP$'),
 ('all-time', 'JJ'),
 ('favorite', 'JJ'),
 ('movie', 'NN'),
 (',', ','),
 ('a', 'DT'),
 ('story', 'NN'),
 ('of', 'IN'),
 ('selflessness', 'NN')]

In [9]:
from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

sia = SentimentIntensityAnalyzer()

In [10]:
sia.polarity_scores('I am so happy!')

{'neg': 0.0, 'neu': 0.318, 'pos': 0.682, 'compound': 0.6468}

In [11]:
sia.polarity_scores('This is the worst thing ever.')

{'neg': 0.451, 'neu': 0.549, 'pos': 0.0, 'compound': -0.6249}

In [12]:
sia.polarity_scores(example)

{'neg': 0.017, 'neu': 0.758, 'pos': 0.225, 'compound': 0.9828}

In [13]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ritika\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
print(example)

Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it's not preachy or boring. It just never gets old, despite my having seen it some 15 or more times in the last 25 years. Paul Lukas' performance brings tears to my eyes, and Bette Davis, in one of her very few truly sympathetic roles, is a delight. The kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. And the mother's slow awakening to what's happening in the world and under her own roof is believable and startling. If I had a dozen thumbs, they'd all be "up" for this movie.


In [15]:
from nltk.tokenize import sent_tokenize, word_tokenize
sents=sent_tokenize(example)

In [16]:
sents

["Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it's not preachy or boring.",
 'It just never gets old, despite my having seen it some 15 or more times in the last 25 years.',
 "Paul Lukas' performance brings tears to my eyes, and Bette Davis, in one of her very few truly sympathetic roles, is a delight.",
 'The kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch.',
 "And the mother's slow awakening to what's happening in the world and under her own roof is believable and startling.",
 'If I had a dozen thumbs, they\'d all be "up" for this movie.']

In [17]:
word=word_tokenize(example)
word

['Probably',
 'my',
 'all-time',
 'favorite',
 'movie',
 ',',
 'a',
 'story',
 'of',
 'selflessness',
 ',',
 'sacrifice',
 'and',
 'dedication',
 'to',
 'a',
 'noble',
 'cause',
 ',',
 'but',
 'it',
 "'s",
 'not',
 'preachy',
 'or',
 'boring',
 '.',
 'It',
 'just',
 'never',
 'gets',
 'old',
 ',',
 'despite',
 'my',
 'having',
 'seen',
 'it',
 'some',
 '15',
 'or',
 'more',
 'times',
 'in',
 'the',
 'last',
 '25',
 'years',
 '.',
 'Paul',
 'Lukas',
 "'",
 'performance',
 'brings',
 'tears',
 'to',
 'my',
 'eyes',
 ',',
 'and',
 'Bette',
 'Davis',
 ',',
 'in',
 'one',
 'of',
 'her',
 'very',
 'few',
 'truly',
 'sympathetic',
 'roles',
 ',',
 'is',
 'a',
 'delight',
 '.',
 'The',
 'kids',
 'are',
 ',',
 'as',
 'grandma',
 'says',
 ',',
 'more',
 'like',
 '``',
 'dressed-up',
 'midgets',
 "''",
 'than',
 'children',
 ',',
 'but',
 'that',
 'only',
 'makes',
 'them',
 'more',
 'fun',
 'to',
 'watch',
 '.',
 'And',
 'the',
 'mother',
 "'s",
 'slow',
 'awakening',
 'to',
 'what',
 "'s",
 'ha

In [18]:
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))

In [19]:
words=[]
for w in word:
    if w not in stopwords:
        print(w)
        words.append(w)

Probably
all-time
favorite
movie
,
story
selflessness
,
sacrifice
dedication
noble
cause
,
's
preachy
boring
.
It
never
gets
old
,
despite
seen
15
times
last
25
years
.
Paul
Lukas
'
performance
brings
tears
eyes
,
Bette
Davis
,
one
truly
sympathetic
roles
,
delight
.
The
kids
,
grandma
says
,
like
``
dressed-up
midgets
''
children
,
makes
fun
watch
.
And
mother
's
slow
awakening
's
happening
world
roof
believable
startling
.
If
I
dozen
thumbs
,
'd
``
''
movie
.


In [20]:
words

['Probably',
 'all-time',
 'favorite',
 'movie',
 ',',
 'story',
 'selflessness',
 ',',
 'sacrifice',
 'dedication',
 'noble',
 'cause',
 ',',
 "'s",
 'preachy',
 'boring',
 '.',
 'It',
 'never',
 'gets',
 'old',
 ',',
 'despite',
 'seen',
 '15',
 'times',
 'last',
 '25',
 'years',
 '.',
 'Paul',
 'Lukas',
 "'",
 'performance',
 'brings',
 'tears',
 'eyes',
 ',',
 'Bette',
 'Davis',
 ',',
 'one',
 'truly',
 'sympathetic',
 'roles',
 ',',
 'delight',
 '.',
 'The',
 'kids',
 ',',
 'grandma',
 'says',
 ',',
 'like',
 '``',
 'dressed-up',
 'midgets',
 "''",
 'children',
 ',',
 'makes',
 'fun',
 'watch',
 '.',
 'And',
 'mother',
 "'s",
 'slow',
 'awakening',
 "'s",
 'happening',
 'world',
 'roof',
 'believable',
 'startling',
 '.',
 'If',
 'I',
 'dozen',
 'thumbs',
 ',',
 "'d",
 '``',
 "''",
 'movie',
 '.']

In [21]:
from nltk.stem.porter import *
p_stemmer = PorterStemmer()
for word in words:
    print(word+' -->' +p_stemmer.stem(word))

Probably -->probabl
all-time -->all-tim
favorite -->favorit
movie -->movi
, -->,
story -->stori
selflessness -->selfless
, -->,
sacrifice -->sacrific
dedication -->dedic
noble -->nobl
cause -->caus
, -->,
's -->'s
preachy -->preachi
boring -->bore
. -->.
It -->it
never -->never
gets -->get
old -->old
, -->,
despite -->despit
seen -->seen
15 -->15
times -->time
last -->last
25 -->25
years -->year
. -->.
Paul -->paul
Lukas -->luka
' -->'
performance -->perform
brings -->bring
tears -->tear
eyes -->eye
, -->,
Bette -->bett
Davis -->davi
, -->,
one -->one
truly -->truli
sympathetic -->sympathet
roles -->role
, -->,
delight -->delight
. -->.
The -->the
kids -->kid
, -->,
grandma -->grandma
says -->say
, -->,
like -->like
`` -->``
dressed-up -->dressed-up
midgets -->midget
'' -->''
children -->children
, -->,
makes -->make
fun -->fun
watch -->watch
. -->.
And -->and
mother -->mother
's -->'s
slow -->slow
awakening -->awaken
's -->'s
happening -->happen
world -->world
roof -->roof
believable 

In [22]:
import nltk
from nltk.stem.porter import *
p_stemmer = PorterStemmer()
for word in words:
    print(p_stemmer.stem(word))

probabl
all-tim
favorit
movi
,
stori
selfless
,
sacrific
dedic
nobl
caus
,
's
preachi
bore
.
it
never
get
old
,
despit
seen
15
time
last
25
year
.
paul
luka
'
perform
bring
tear
eye
,
bett
davi
,
one
truli
sympathet
role
,
delight
.
the
kid
,
grandma
say
,
like
``
dressed-up
midget
''
children
,
make
fun
watch
.
and
mother
's
slow
awaken
's
happen
world
roof
believ
startl
.
if
i
dozen
thumb
,
'd
``
''
movi
.


In [23]:
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
for word in words:
    print(word+' --> '+ lemmatizer.lemmatize(word))

Probably --> Probably
all-time --> all-time
favorite --> favorite
movie --> movie
, --> ,
story --> story
selflessness --> selflessness
, --> ,
sacrifice --> sacrifice
dedication --> dedication
noble --> noble
cause --> cause
, --> ,
's --> 's
preachy --> preachy
boring --> boring
. --> .
It --> It
never --> never
gets --> get
old --> old
, --> ,
despite --> despite
seen --> seen
15 --> 15
times --> time
last --> last
25 --> 25
years --> year
. --> .
Paul --> Paul
Lukas --> Lukas
' --> '
performance --> performance
brings --> brings
tears --> tear
eyes --> eye
, --> ,
Bette --> Bette
Davis --> Davis
, --> ,
one --> one
truly --> truly
sympathetic --> sympathetic
roles --> role
, --> ,
delight --> delight
. --> .
The --> The
kids --> kid
, --> ,
grandma --> grandma
says --> say
, --> ,
like --> like
`` --> ``
dressed-up --> dressed-up
midgets --> midget
'' --> ''
children --> child
, --> ,
makes --> make
fun --> fun
watch --> watch
. --> .
And --> And
mother --> mother
's --> 's
slow --

In [24]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ritika\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [25]:
words_l=[]
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
for word in words:
    print(lemmatizer.lemmatize(word))
    words_l.append(word)

Probably
all-time
favorite
movie
,
story
selflessness
,
sacrifice
dedication
noble
cause
,
's
preachy
boring
.
It
never
get
old
,
despite
seen
15
time
last
25
year
.
Paul
Lukas
'
performance
brings
tear
eye
,
Bette
Davis
,
one
truly
sympathetic
role
,
delight
.
The
kid
,
grandma
say
,
like
``
dressed-up
midget
''
child
,
make
fun
watch
.
And
mother
's
slow
awakening
's
happening
world
roof
believable
startling
.
If
I
dozen
thumb
,
'd
``
''
movie
.


In [26]:
words_l

['Probably',
 'all-time',
 'favorite',
 'movie',
 ',',
 'story',
 'selflessness',
 ',',
 'sacrifice',
 'dedication',
 'noble',
 'cause',
 ',',
 "'s",
 'preachy',
 'boring',
 '.',
 'It',
 'never',
 'gets',
 'old',
 ',',
 'despite',
 'seen',
 '15',
 'times',
 'last',
 '25',
 'years',
 '.',
 'Paul',
 'Lukas',
 "'",
 'performance',
 'brings',
 'tears',
 'eyes',
 ',',
 'Bette',
 'Davis',
 ',',
 'one',
 'truly',
 'sympathetic',
 'roles',
 ',',
 'delight',
 '.',
 'The',
 'kids',
 ',',
 'grandma',
 'says',
 ',',
 'like',
 '``',
 'dressed-up',
 'midgets',
 "''",
 'children',
 ',',
 'makes',
 'fun',
 'watch',
 '.',
 'And',
 'mother',
 "'s",
 'slow',
 'awakening',
 "'s",
 'happening',
 'world',
 'roof',
 'believable',
 'startling',
 '.',
 'If',
 'I',
 'dozen',
 'thumbs',
 ',',
 "'d",
 '``',
 "''",
 'movie',
 '.']

In [27]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

no_punct = " "
for char in words_l:
    if char not in punctuations:
        no_punct = no_punct + char
        
print(no_punct)

 Probablyall-timefavoritemoviestoryselflessnesssacrificededicationnoblecause'spreachyboringItnevergetsolddespiteseen15timeslast25yearsPaulLukasperformancebringstearseyesBetteDavisonetrulysympatheticrolesdelightThekidsgrandmasayslike``dressed-upmidgets''childrenmakesfunwatchAndmother'sslowawakening'shappeningworldroofbelievablestartlingIfIdozenthumbs'd``''movie


In [28]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [29]:
y=df['sentiment']

In [30]:
df['sentiment'].value_counts(),df['sentiment'].nunique()

(positive    25000
 negative    25000
 Name: sentiment, dtype: int64,
 2)

In [31]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [32]:
df.shape

(50000, 2)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [34]:
text=df['review']

In [35]:
text=text.str.lower()

In [36]:
import re
def remove_html_tags(text):
    pattern =re.compile('<.?>')
    return pattern.sub(r'',text)

In [37]:
text=text.apply(remove_html_tags)
text

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [38]:
text[7606].encode('utf-8')

b'the main character, pharaon, has suffered a loss of his wife and child in the pre-film past. he deals with with by just shutting down emotionally. too long a movie, too much time spent on pharaon\'s inexpressive face, too much "road time" (one of the banes of tv: filling time with moving cars, trains, etc.) long scenes of him doing trivial - sometimes totally inexplicable, nonsensically trivial - actions with neither reason or emotion. his best friends joseph and domino are not much more, their relationship based on sex (this film perhaps gives new meaning to the phrase "gratuitous sex"); domino and pharaon\'s mother are the two characters who display some emotion, but not much. it is hard to tell with all the characters in this movie: is it indifferent acting, indifferent writing, or simply indifferent characters portrayed by good writing and good acting. characters in this film talk very little to anyone; it\'s little wonder their emotionally isolated, which is all the more bizarre

In [39]:
type(text)

pandas.core.series.Series

In [40]:
test=[[text]]

In [41]:
text

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [42]:
text=pd.DataFrame(text)
text

review
0      one of the other reviewers has mentioned that ...
1      a wonderful little production. <br /><br />the...
2      i thought this was a wonderful way to spend ti...
3      basically there's a family where a little boy ...
4      petter mattei's "love in the time of money" is...
...                                                  ...
49995  i thought this movie did a down right good job...
49996  bad plot, bad dialogue, bad acting, idiotic di...
49997  i am a catholic taught in parochial elementary...
49998  i'm going to have to disagree with the previou...
49999  no one expects the star trek movies to be high...

[50000 rows x 1 columns]

In [43]:
type(text)

pandas.core.frame.DataFrame

In [44]:
text.shape

(50000, 1)

In [45]:
text[19606:19607]

review
19606  this movie is fun to watch. if you liked "dave...

In [46]:
text.shape

(50000, 1)

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
cv=CountVectorizer()
x1= cv.fit_transform(text['review'])
x1.shape

(50000, 101895)

In [49]:
x1

<50000x101895 sparse matrix of type '<class 'numpy.int64'>'
	with 6826529 stored elements in Compressed Sparse Row format>

In [50]:
text[['review']]

review
0      one of the other reviewers has mentioned that ...
1      a wonderful little production. <br /><br />the...
2      i thought this was a wonderful way to spend ti...
3      basically there's a family where a little boy ...
4      petter mattei's "love in the time of money" is...
...                                                  ...
49995  i thought this movie did a down right good job...
49996  bad plot, bad dialogue, bad acting, idiotic di...
49997  i am a catholic taught in parochial elementary...
49998  i'm going to have to disagree with the previou...
49999  no one expects the star trek movies to be high...

[50000 rows x 1 columns]

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [52]:
tr_idf_model = TfidfVectorizer()
tf_idf = tr_idf_model.fit_transform(text['review'])

In [53]:
tf_idf.size

6826529

In [54]:
print(type(tf_idf), tf_idf.shape)

<class 'scipy.sparse._csr.csr_matrix'> (50000, 101895)


In [55]:
from keras.utils import np_utils
npy=np_utils.to_categorical(y)
print(npy[:5])

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x1, npy,test_size=.25,random_state=15)

In [57]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(37500, 101895)
(12500, 101895)
(37500, 2)
(12500, 2)


In [58]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler(with_mean=False)
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [59]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(37500, 101895)
(12500, 101895)
(37500, 2)
(12500, 2)


In [60]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Activation,Dropout
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

In [61]:
model = Sequential()
model.add(Dense(units=20,activation='relu', input_dim=101895))
model.add(Dropout(0.1))
model.add(Dense(units=2,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(units=2,activation='sigmoid'))

In [62]:
model.compile(optimizer='Adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [63]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                2037920   
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 2)                 42        
                                                                 
 dropout_1 (Dropout)         (None, 2)                 0         
                                                                 
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
Total params: 2,037,968
Trainable params: 2,037,968
Non-trainable params: 0
_________________________________________________________________


In [64]:
d=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=3)

Epoch 1/3
1172/1172 [==============================] - 41s 33ms/step - loss: 0.4541 - accuracy: 0.7828 - val_loss: 0.3933 - val_accuracy: 0.8382
Epoch 2/3
1172/1172 [==============================] - 40s 34ms/step - loss: 0.2424 - accuracy: 0.8827 - val_loss: 0.3868 - val_accuracy: 0.8637
Epoch 3/3
1172/1172 [==============================] - 39s 33ms/step - loss: 0.1511 - accuracy: 0.9164 - val_loss: 0.4604 - val_accuracy: 0.8640


In [65]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(lowercase=True,stop_words='english',ngram_range=(1,1))
X= cv.fit_transform(text['review'])

In [66]:
X

<50000x101583 sparse matrix of type '<class 'numpy.int64'>'
	with 4434500 stored elements in Compressed Sparse Row format>

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
tf=TfidfVectorizer()
X=tf.fit_transform(text['review'])
X

<50000x101895 sparse matrix of type '<class 'numpy.float64'>'
	with 6826529 stored elements in Compressed Sparse Row format>

In [69]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(df['sentiment'])
y

array([1, 1, 1, ..., 0, 0, 0])

In [70]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(X, y, test_size=.25)

In [71]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(37500, 101895)
(12500, 101895)
(37500,)
(12500,)


In [72]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler(with_mean=False)
x_train = sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [73]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [74]:
nb= MultinomialNB().fit(x_train,y_train)
nb

MultinomialNB()

In [75]:
nb.score(x_test,y_test)

0.73904

In [76]:
y_pred_nb=nb.predict(x_test)
print(len(y_pred_nb))
y_pred_nb

12500


array([1, 1, 0, ..., 0, 1, 1])

In [77]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [78]:
metrics.accuracy_score(y_test,y_pred_nb)

0.73904

In [79]:
print(confusion_matrix(y_test,y_pred_nb))

[[4724 1563]
 [1699 4514]]
